### ISSUE TITLE
Process hacking

### ISSUE THREAD

**Issue by 25094** [hrydgard/ppsspp-site#13]
The script in the process hacking section is unnecessary as you can implement the sendmessage call inside of cheat engine.

### Script
```
function GetEmuBase()
local command = 0xB118
local emuHWND = findWindow("PPSSPPWnd")

local pointer = {}

local result = sendMessage(emuHWND, command, 0, 0)
pointer[1] = tonumber(result)

result = sendMessage(emuHWND, command, 0, 1)
pointer[2] = tonumber(result)

local lower = pointer[1]
local upper = pointer[2]
local combinedPointer = (upper * 0x100000000) + lower

return tonumber(combinedPointer)
end
```

You can add this inside of any auto assembler script at the start or inside the enable part and it should run fine if you remember to add {$lua} before adding the code.

**Comment by hrydgard** [comment]
please feel free to send a pull request instead with the changes so they get properly credited, or I can just manually add this for you - which do you prefer?

**Comment by 25094** [comment]
I'm new to github so could you please manually add it, I don't usually use github but I am modding in ppssspp at the moment. I used the process hacking section to implement the sendmessage inside of a c++ tool so it caught me off guard that it was updated with a script for autohotkey.

**Comment by hrydgard** [comment]
Alright, I'll add it. I'll keep the autohotkey script, too - why not, there might be some other use for it.

**Comment by 25094** [comment]
Thanks! and sure the autohotkey might be able to automate some stuff that normal lua scripts couldn't.

**Comment by hrydgard** [comment]
change is live.

**Comment by Nokhwabuz** [comment]
Thanks siyabonga
