### ISSUE TITLE
incorrect handling of empty email field on login page 

### ISSUE THREAD

**Issue by CarlosZBent** [hrydgard/ppsspp-site#14]
If the user attempts lo log in using an email but not a password, the validation works and it show an error saying *"You must provide both email and password."* But if both email and password are missing, the validation fails and it shows this in dev mode:

![image](https://github.com/hrydgard/ppsspp-site/assets/72584905/7f7bcbf0-ee5d-4209-b209-e06d5c8468bd)

and this in prod (while not showing any error on screen):
![image](https://github.com/hrydgard/ppsspp-site/assets/72584905/1711019d-4876-4db8-9f50-03d008c13691)

**Comment by hrydgard** [comment]
Will actually deploy the fix tomorrow.
