### ISSUE TITLE
Is there a way to launch eboot.pbp games?

### ISSUE THREAD

**Issue by SeledOchko** [hrydgard/ppsspp-site#29]
I found a game for ps1, converted into a psp game as an eboot.pbp file (the game is jojo's bizarre adventures fighting). I tried to convert it into .iso via eboot2pbp converter, but when i launch the game there's just black screen. However it shows the icon of the game on the list in main menu. Is it possible to prepare the file properly or fix it so i can play?

**Comment by hrydgard** [comment]
PPSSPP is a PSP emulator. It doesn't run PS1 game even if you pack them in a PBP, sorry.

The real PSP has a built-in PS1 emulator, but we can't include that.
