### ISSUE TITLE
Download buttons don't do anything on Firefox

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp-site#3]
Very strange, as they're just `<a>` links styled as buttons...

**Comment by unknownbrackets** [comment]
Well, "Download APK of PPSSPP Free" has no href so it doesn't work.  Same for the Windows ones.  This makes them not work in Chrome or Firefox, for me.

-[Unknown]

**Comment by hrydgard** [comment]
Oh crap, got lost when I switched from nested `a` and `button` tags, to just `a` tags styled as buttons. Fixing.
