### ISSUE TITLE
Add F-Droid to the downloads page

### ISSUE THREAD

**Issue by licaon-kter** [hrydgard/ppsspp-site#33]
here: https://www.ppsspp.org/download/

F-Droid link: https://f-droid.org/packages/org.ppsspp.ppsspp/

F-Droid badge: https://gitlab.com/fdroid/artwork/-/tree/master/badge?ref_type=heads

**Comment by hrydgard** [comment]
Fixed by 3c926a0c8c7d687afd1e3766a6528d6c70dd55ab
