### ISSUE TITLE
Add Flatpak badge to the download button for Linux 

### ISSUE THREAD

**Issue by CharDSonDev** [hrydgard/ppsspp-site#4]
Flathub provides badges for the buttons that redirect to Flathub which is where the Linux version of PPSSPP provided on the PPSSPP site is hosted.

Adding the badge will make it easier to identify the Linux button.

Here you can find the Flathub badge: https://flathub.org/badges

**Comment by hrydgard** [comment]
Done and deployed, thanks for the suggestion.
